### ISSUE TITLE
Docs: Session without SessionMiddleware

### ISSUE THREAD

**Issue by mj4444ru** [yiisoft/session#18]
At the moment, the `Session` class cannot function on its own without `SessionMiddleware`, since the `Session::setId` method must be called to work correctly with sessions.

I suggest adding a section to [README.md] (/yiisoft/session/blob/master/README.md):

#### Using Session without SessionMiddleware

If you want to use the functionality of the `Session` class without the `SessionMiddleware` class, you need to get the session identifier yourself (from the request) when creating the `Session` instance (or before using it for the first time) and pass it to the `Session` class instance via the `Session::setId` method.

--------

На данный момент класс `Session` не может функционировать самостоятельно без `SessionMiddleware`, так как для корректной работы с сессиями требуется вызов метода `Session::setId`.

Предлагаю добавить в [README.md](/yiisoft/session/blob/master/README.md) раздел:

#### Использование Session без SessionMiddleware

Если вы хотите использовать функционал класса `Session` без класса `SessionMiddleware`, вам необходимо при создании экземпляра `Session` (или до первого его использования), самостоятельно получить идентификатор сессии (из запроса) и передать его в экземпляр класса `Session` через метод `Session::setId`.

**Comment by samdark** [comment]
What's the use case of not using the middleware?

**Comment by mj4444ru** [comment]
It is impossible to envisage all use cases. The availability of additional documentation is never superfluous, including for understanding how it works and interacts with each other in general.

**Comment by mj4444ru** [comment]
I also think that the documentation lacks information that when using the API on the site, it may be worth adding `MiddlewareDispatcher::class` to the routes that only refer to the web part of the site.

**Comment by mj4444ru** [comment]
I also think that the documentation lacks information that when using the API on the site, it may be worth adding `SessionMiddleware` to the routes that only refer to the web part of the site.
When using `SessionMiddleware` globally, due to an error in the code, each API call can create a new session, which will lead to significant additional resource consumption.
