### ISSUE TITLE
Calling $session->close() for the first request doesn't set up cookie

### ISSUE THREAD

**Issue by dmotitsk** [yiisoft/session#32]
Prerequisite:
There is no session cookie set up for the domain using for test.

Steps to reproduce:
Add SessionMiddleware to the middlewares used by the application

In the controller call:
1. $session->open();
2. $session->set('key', 'value');
3. $session->close();

Expected result: there is a Set-Cookie header (PHPSESSID) in the response.

Actual result: there is no Set-Cookie header in the response.

It is said in the documentation:
> Note: Closing session as early as possible is a good practice since many session implementations are blocking other requests while session is open.

It shoud be either fixed in the documentation to forbid closing session manually, or should be fixed in the code to send a cookie for a manually closed session.

**Comment by vjik** [comment]
In session middleware we should check `getId` is not null in additional to `isActive`
